language: python
python: "3.7-dev"  # 3.7 development branch
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
  - pip install pipenv
  - pipenv install
script: lektor build -f webpack
deploy:
  provider: script
  script: lektor deploy ghpages
