name: Building and Deploying to CC opensource site
on: [push]
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - name: Lektor Action
     uses: VaultVulp/lektor-action@v1.0.2
   - name: Start webpack build
     run: |
      lektor server -f webpack
